### PR TITLE
Create Dijkstra's Algorithm

### PR DESCRIPTION
**Pull request by deepak74620**
Dijkstra's Algorithm to find Shortest Paths from Source to all Vertices

### CODE REVIEW

**Comment by Namya13Jain** [comment]
Hey @deepak74620, great initiative but please write the code in C++ language. And just add the space and time complexity of the your code as comments.

**Comment by AhtishamJaved** [comment]
#include <iostream>
#include <vector>
#include <queue>
#include <climits>

using namespace std;

#define INF INT_MAX

class Graph {
public:
    int V;
    vector<vector<pair<int, int>>> adj;

    Graph(int V);

    void addEdge(int u, int v, int w);

    void dijkstra(int src);
};

Graph::Graph(int V) {
    this->V = V;
    adj.resize(V);
}

void Graph::addEdge(int u, int v, int w) {
    adj[u].push_back(make_pair(v, w));
    adj[v].push_back(make_pair(u, w));
}

void Graph::dijkstra(int src) {
    vector<int> dist(V, INF);
    vector<bool> visited(V, false);
    priority_queue<pair<int, int>, vector<pair<int, int>>, greater<pair<int, int>>> pq;

    dist[src] = 0;
    pq.push(make_pair(0, src));

    while (!pq.empty()) {
        int u = pq.top().second;
        pq.pop();

        if (visited[u])
            continue;

        visited[u] = true;

        for (const auto &pair : adj[u]) {
            int v = pair.first;
            int weight = pair.second;

            if (!visited[v] && dist[u] != INF && dist[u] + weight < dist[v]) {
                dist[v] = dist[u] + weight;
                pq.push(make_pair(dist[v], v));
            }
        }
    }

    cout << "Vertex   Distance from Source\n";
    for (int i = 0; i < V; i++)
        cout << i << "\t\t" << dist[i] << endl;
}

int main() {
    int V = 9;
    Graph g(V);

    //add edge in this format (g.addEdge(0, 1, 4);)
   

    //return 0;
}
//Time Complexity: O(V^2) (for the adjacency matrix implementation) or O((V + E) * log(V)) (for the adjacency list //implementation with a min-priority queue).
//Space Complexity: O(V^2) (for the adjacency matrix implementation) or O(V + E) (for the adjacency list implementation)

**Comment by AhtishamJaved** [comment]
#include
#include
#include
#include

using namespace std;

#define INF INT_MAX

class Graph {
public:
int V;
vector<vector<pair<int, int>>> adj;

Graph(int V);

void addEdge(int u, int v, int w);

void dijkstra(int src);
};

Graph::Graph(int V) {
this->V = V;
adj.resize(V);
}

void Graph::addEdge(int u, int v, int w) {
adj[u].push_back(make_pair(v, w));
adj[v].push_back(make_pair(u, w));
}

void Graph::dijkstra(int src) {
vector dist(V, INF);
vector visited(V, false);
priority_queue<pair<int, int>, vector<pair<int, int>>, greater<pair<int, int>>> pq;

dist[src] = 0;
pq.push(make_pair(0, src));

while (!pq.empty()) {
    int u = pq.top().second;
    pq.pop();

    if (visited[u])
        continue;

    visited[u] = true;

    for (const auto &pair : adj[u]) {
        int v = pair.first;
        int weight = pair.second;

        if (!visited[v] && dist[u] != INF && dist[u] + weight < dist[v]) {
            dist[v] = dist[u] + weight;
            pq.push(make_pair(dist[v], v));
        }
    }
}

cout << "Vertex   Distance from Source\n";
for (int i = 0; i < V; i++)
    cout << i << "\t\t" << dist[i] << endl;
}

int main() {
int V = 9;
Graph g(V);

//add edge in this format (g.addEdge(0, 1, 4);)


//return 0;
}
//Time Complexity: O(V^2) (for the adjacency matrix implementation) or O((V + E) * log(V)) (for the adjacency list //implementation with a min-priority queue).
//Space Complexity: O(V^2) (for the adjacency matrix implementation) or O(V + E) (for the adjacency list implementation)

**Comment by AhtishamJaved** [comment]
#include
#include
#include
#include

using namespace std;

#define INF INT_MAX

class Graph {
public:
int V;
vector<vector<pair<int, int>>> adj;

Graph(int V);

void addEdge(int u, int v, int w);

void dijkstra(int src);
};

Graph::Graph(int V) {
this->V = V;
adj.resize(V);
}

void Graph::addEdge(int u, int v, int w) {
adj[u].push_back(make_pair(v, w));
adj[v].push_back(make_pair(u, w));
}

void Graph::dijkstra(int src) {
vector dist(V, INF);
vector visited(V, false);
priority_queue<pair<int, int>, vector<pair<int, int>>, greater<pair<int, int>>> pq;

dist[src] = 0;
pq.push(make_pair(0, src));

while (!pq.empty()) {
    int u = pq.top().second;
    pq.pop();

    if (visited[u])
        continue;

    visited[u] = true;

    for (const auto &pair : adj[u]) {
        int v = pair.first;
        int weight = pair.second;

        if (!visited[v] && dist[u] != INF && dist[u] + weight < dist[v]) {
            dist[v] = dist[u] + weight;
            pq.push(make_pair(dist[v], v));
        }
    }
}

cout << "Vertex   Distance from Source\n";
for (int i = 0; i < V; i++)
    cout << i << "\t\t" << dist[i] << endl;
}

int main() {
int V = 9;
Graph g(V);

//add edge in this format (g.addEdge(0, 1, 4);)


//return 0;
}
//Time Complexity: O(V^2) (for the adjacency matrix implementation) or O((V + E) * log(V)) (for the adjacency list //implementation with a min-priority queue).
//Space Complexity: O(V^2) (for the adjacency matrix implementation) or O(V + E) (for the adjacency list implementation)

**Comment by deepak74620** [comment]
Thanks for the suggestion. Changed the code with added comments for complexity.

**Pull request merged**
